global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: https
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - prometheus.nibies.space

- job_name: cadvisor
  scrape_interval: 5s
  scheme: https
  static_configs:
  - targets:
    - cadvisor.nibies.space
    
- job_name: node_exporter
  scrape_interval: 5s
  # scheme: https
  static_configs:
  - targets:
    - node_exporter:9100